# Copyright 2017, 2019, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

#cloud-config
package_upgrade: ${operator_upgrade}
timezone: ${timezone}
write_files:
# setup script
  - path: "/root/operator/operator.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${operator_sh_content}
runcmd:
 - echo "Configuring operator..."
 - bash /root/operator/operator.sh
 - echo "export OCI_CLI_AUTH=instance_principal" >>  /home/opc/.bashrc
 - touch /home/opc/operator.finish