# Copyright 2017, 2021, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

#cloud-config
package_upgrade: ${upgrade_operator}
timezone: ${operator_timezone}
packages:
  - python3-oci-cli

bootcmd:
  - [dnf, config-manager, --enable, ol8_developer]
  - [uptrack-upgrade, -y]

runcmd:
 - echo "Setting instance_principal..."
 - echo "export OCI_CLI_AUTH=instance_principal" >>  /home/opc/.bashrc
 - touch /home/opc/operator.finish

final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime